### ISSUE TITLE
The guards at Ardougne are aggressive

### ISSUE THREAD

**Issue by Gptaqbc** [2006rebotted/2006rebotted#223]

**Comment by DPSCryptic** [comment]
must have happened while someone worked on some aggression issues, wasnt before

**Comment by Gptaqbc** [comment]
It is indeed related to the rework that was done on the aggressive monsters. I'll provide the ID asap!

**Comment by Gptaqbc** [comment]
ID = 32. Only aggressive when cmb level is < 2X npc level

**Comment by DPSCryptic** [comment]
maybe we should make zones where that counts, like bank zones

**Comment by mrextremez** [comment]
From testing it a bit it looks like only one of the guards are aggressive and not any  of the others. Very strange given that they are all the same npc id from what I can tell

**Comment by Gptaqbc** [comment]
That's funny

**Comment by Gptaqbc** [comment]
What if we simply remove that NPC spawn?

**Comment by mrextremez** [comment]
I suppose you could do that lol

**Comment by SandroCoutinho** [comment]
Issue was caused due to the wrong parameter being given to the 2 different methods.
It was grabbing the mugger's id(175) instead of the guards one(32).

```                if (client != null) {
                    System.out.println("npc id " + i);
                    boolean aggressive = (NpcAggressive.isAggressive(i) || getNpcListCombat(npcs[i].npcType) * 2 > client.combatLevel && getNpcListAggressive(i));
                    System.out.println("is aggressive: " + aggressive);```
